apiVersion: v1
kind: Secret
metadata:
    name: zerossl-eabsecret
    namespace: cert-manager
data:
    secret: ENC[AES256_GCM,data:Dzpzig/mkyy8GU4E8tnsL8NNb0ZKakdeS1gDjQH3LSLVOlMKuIj3CEo7q7sWxbu5ykvPfaHc6oEsMgSPoAvrrJhFcs15alt0/iNtI67GXxBuhO1NHQ91ItmZiMGaRV7QGNJm2k4DRkjSPofxJ16AAOWs8Ds=,iv:eOf6rW5dMvhkLlePHanXeLpy8cqQ+SIyQ/pztkSwsgQ=,tag:DzzmYuSpczxaxMrqGvWHuA==,type:str]
type: Opaque
sops:
    age:
        - recipient: age1u58nleqhzvf90aky87lwsxx0ty92sp264ravzxmswdtkla9dx5usk9krj2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPU3hTOVFzVFBTL1d0blNY
            NlN3amdYV0lXdERROFBiaTV6N0xINVBGUEJFCjlFMnF0aHJHZit6S280czNCRk1W
            Tm1QdWNIOHBLTzVIbU5Gb3crc3g3WjQKLS0tIDRvNDRKMDBoamNEZ1BXQkNZbGNI
            aHA5bENzdTZyQVdQUWVyNXc1czRFdDQKy4w5ALpTPdolrJQIp534BRjJr+2+3ChO
            9uiUXWTvR+TaMg63q3R2ocJoQZwTcxOVlYHT1EQLj+FdeoxPG1fHmQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-27T19:46:45Z"
    mac: ENC[AES256_GCM,data:4iIz8yf9zggDoMIgBRmPbsNd0604oomKThNzxwDKzplCGYMEoC8Nqt+o8gsmRjMnkkAIzgfwPKfIrxSfityuLvX4ymBMkjqxETRFgv972K7ZR4tsZHtXo/gWpOg6O3bTZZ48REbfgmPGsPIYiOEGcAMCgMjedu4A8ByBL5xOMuY=,iv:wwNZOaehx8OvBCoPVhPv2rUqKAbhQqlns6lShmqISPU=,tag:Z7TjNug2BXHF6LvbPJ6Szg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
